name: open_meteo_api
description: A dart API Client for the Open-Meteo API.
version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  test: ^1.22.0
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
